/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Logica.Controler;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.UIManager;

/**
 *
 * @author cesar
 */
public class InitialFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitialFrame
     */
    public InitialFrame() {
        UIManager.put("ScrollBarUI", "javax.swing.plaf.basic.BasicScrollBarUI"); // Cambiar Scroll por defecto
        initComponents();
        getContentPane().setBackground(Color.white);
        setVisible(true);
    }

    public void limpiarFrame(){
        this.txAreaBayas.setText("");
        this.txAreaFloracion.setText("");
        this.txAreaHabito.setText("");
        this.txAreaTuberculos.setText("");
    }
    
    public void mensajeEmergente(String m){
        JOptionPane.showMessageDialog(null, m);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertar = new javax.swing.JButton();
        labFloracion = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        labBayas = new javax.swing.JLabel();
        labTuberculos = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldEspecie = new javax.swing.JTextField();
        labTitulo = new javax.swing.JLabel();
        fieldZonaProd = new javax.swing.JTextField();
        labInicializar = new javax.swing.JLabel();
        labNombre = new javax.swing.JLabel();
        labEspecie = new javax.swing.JLabel();
        labZonaProd = new javax.swing.JLabel();
        labHabito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAreaFloracion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txAreaHabito = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txAreaBayas = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txAreaTuberculos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertar.setBackground(new java.awt.Color(255, 255, 255));
        btnInsertar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(13, 24, 89));
        btnInsertar.setText("Insertar");
        btnInsertar.setActionCommand("InsertarInitial");
        btnInsertar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 24, 89), 1, true));
        btnInsertar.setContentAreaFilled(false);

        labFloracion.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labFloracion.setText("Floración");

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(13, 24, 89));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setActionCommand("LimpiarInitial");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 24, 89)));
        btnLimpiar.setContentAreaFilled(false);

        labBayas.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labBayas.setText("Bayas");

        labTuberculos.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labTuberculos.setText("Tubérculos");

        fieldNombre.setEditable(false);
        fieldNombre.setFocusable(false);

        fieldEspecie.setEditable(false);
        fieldEspecie.setFocusable(false);

        labTitulo.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        labTitulo.setText("Insertar datos:");

        fieldZonaProd.setEditable(false);
        fieldZonaProd.setFocusable(false);

        labInicializar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        labInicializar.setForeground(new java.awt.Color(13, 24, 89));
        labInicializar.setText("Inicializar gestor de papas");

        labNombre.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labNombre.setText("Nombre:");

        labEspecie.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labEspecie.setText("Especie:");

        labZonaProd.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labZonaProd.setText("Zona de producción:");

        labHabito.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        labHabito.setText("Hábito de crecimiento");

        txAreaFloracion.setColumns(20);
        txAreaFloracion.setLineWrap(true);
        txAreaFloracion.setRows(5);
        jScrollPane1.setViewportView(txAreaFloracion);

        txAreaHabito.setColumns(20);
        txAreaHabito.setLineWrap(true);
        txAreaHabito.setRows(5);
        jScrollPane2.setViewportView(txAreaHabito);

        txAreaBayas.setColumns(20);
        txAreaBayas.setLineWrap(true);
        txAreaBayas.setRows(5);
        jScrollPane3.setViewportView(txAreaBayas);

        txAreaTuberculos.setColumns(20);
        txAreaTuberculos.setLineWrap(true);
        txAreaTuberculos.setRows(5);
        jScrollPane4.setViewportView(txAreaTuberculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labInicializar, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labZonaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldZonaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labBayas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(labFloracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(labTuberculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labInicializar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNombre)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEspecie)
                    .addComponent(fieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labZonaProd)
                    .addComponent(fieldZonaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labHabito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labFloracion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labBayas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTuberculos))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInsertar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JTextField fieldEspecie;
    public javax.swing.JTextField fieldNombre;
    public javax.swing.JTextField fieldZonaProd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel labBayas;
    public javax.swing.JLabel labEspecie;
    public javax.swing.JLabel labFloracion;
    public javax.swing.JLabel labHabito;
    public javax.swing.JLabel labInicializar;
    public javax.swing.JLabel labNombre;
    public javax.swing.JLabel labTitulo;
    public javax.swing.JLabel labTuberculos;
    public javax.swing.JLabel labZonaProd;
    public javax.swing.JTextArea txAreaBayas;
    public javax.swing.JTextArea txAreaFloracion;
    public javax.swing.JTextArea txAreaHabito;
    public javax.swing.JTextArea txAreaTuberculos;
    // End of variables declaration//GEN-END:variables
}
